  GNU nano 8.7.1                                          config.yaml                                                   meta:
  version: 3
  flow: Classic

DESIGN_NAME: cts_counter

VERILOG_FILES:
  - dir::src/cts_counter.sv

CLOCK_PORT: clk_i
CLOCK_PERIOD: 20.0

PNR_SDC_FILE: dir::constraint/pnr.sdc
SIGNOFF_SDC_FILE: dir::constraint/signoff.sdc
FALLBACK_SDC: dir::constraint/pnr.sdc

FP_SIZING: relative
FP_CORE_UTIL: 35
FP_ASPECT_RATIO: 1.0
BOTTOM_MARGIN_MULT: 4
TOP_MARGIN_MULT: 4
LEFT_MARGIN_MULT: 12
RIGHT_MARGIN_MULT: 12

PL_TARGET_DENSITY_PCT: 45

RUN_CTS: true
RUN_POST_CTS_RESIZER_TIMING: true

CTS_SINK_CLUSTERING_ENABLE: true
CTS_SINK_CLUSTERING_SIZE: 16
CTS_SINK_CLUSTERING_MAX_DIAMETER: 50
CTS_OBSTRUCTION_AWARE: true
CTS_BALANCE_LEVELS: true
CTS_APPLY_NDR: root_only

PL_RESIZER_SETUP_SLACK_MARGIN: 0.10
PL_RESIZER_HOLD_SLACK_MARGIN: 0.0
PL_RESIZER_ALLOW_SETUP_VIOS: false
GRT_RESIZER_ALLOW_SETUP_VIOS: false

GRT_ALLOW_CONGESTION: false
