create_clock -name core_clk -period 20.000 [get_ports clk_i]
set_clock_uncertainty 0.250 [get_clocks core_clk]
set_clock_transition 0.150 [get_clocks core_clk]
set_input_delay 2.000 -clock core_clk [get_ports counter_enable_i]
set_input_delay 2.000 -clock core_clk [get_ports accum_enable_i]
set_input_delay 2.000 -clock core_clk [get_ports data_i*]
set_input_delay 2.000 -clock core_clk [get_ports select_i]
set_output_delay 4.000 -clock core_clk [get_ports result_o*]
set_load 0.033442 [get_ports result_o*]
set_false_path -from [get_ports rst_ni]
