meta:
  version: 3
  flow: Classic

DESIGN_NAME: macro_wrapper

VERILOG_FILES:
  - dir::src/macro_wrapper.sv

VERILOG_DEFINES:
  - USE_POWER_PINS

CLOCK_PORT: clk_i
CLOCK_PERIOD: 20.0

PNR_SDC_FILE: dir::constraints.sdc
SIGNOFF_SDC_FILE: dir::constraints.sdc
FALLBACK_SDC: dir::constraints.sdc

VDD_NETS:
  - VDD

GND_NETS:
  - VSS

FP_SIZING: absolute
DIE_AREA: [0, 0, 520, 460]
CORE_AREA: [20, 20, 500, 440]

PL_TARGET_DENSITY_PCT: 28
GRT_ALLOW_CONGESTION: false

FP_MACRO_HORIZONTAL_HALO: 15
FP_MACRO_VERTICAL_HALO: 15

PDN_CORE_RING: true
PDN_ENABLE_PINS: true

MACROS:
  counter_macro:
    gds:
      - dir::../macros/counter_macro/gds/counter_macro.gds
    lef:
      - dir::../macros/counter_macro/lef/counter_macro.lef
    vh:
      - dir::src/counter_macro.vh
    nl:
      - dir::../macros/counter_macro/nl/counter_macro.nl.v
    lib: {}
    spef: {}
    spice: []
    sdf: {}
    instances:
      u_counter_macro:
        location: [150, 135]
        orientation: N

PDN_MACRO_CONNECTIONS:
  - "u_counter_macro VDD VSS VDD VSS"

PRIMARY_GDSII_STREAMOUT_TOOL: klayout

RUN_POST_CTS_RESIZER_TIMING: true
RUN_POST_GRT_RESIZER_TIMING: true
